### ISSUE TITLE
define salinity units in attune discrete

### ISSUE THREAD

**Issue by ecrockford** [WHOIGit/nes-lter-attune-fcm-discrete-transect#2]
Error: Data table attributes (attune-transect-discrete-samples.csv, Required) - Data table attributes will be dropped from the EML until these issues are fixed:
1.  Undefined units. Units must be from the EML standard unit dictionary or defined as custom units. The units of these attributes are undefined: salinity

**Comment by sbeaulieu** [comment]
-info.xlsx ColumnHeaders tab:
please change salinity definition to "salinity when rosette bottle closed obtained from CTD bottle file, calculated according to the Practical Salinity Scale of 1978" [this is based on my looking at Seabird software manual "Salinity is PSS-78" and how Santa Barbara Coastal defined salinity from Seabird output]
please change unit to dimensionless

**Comment by ecrockford** [comment]
Applied recommended changes
